"""criando tabela relatorios

Revision ID: a72b674e465a
Revises: 95b5d2d9f7d6
Create Date: 2026-05-17 17:36:44.269111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72b674e465a'
down_revision: Union[str, Sequence[str], None] = '95b5d2d9f7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('exportado_pdf', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatorios_id'), 'relatorios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relatorios_id'), table_name='relatorios')
    op.drop_table('relatorios')
    # ### end Alembic commands ###
